---
name: pre-commit
on: [push, pull_request]
jobs:
  pre-commit-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v2.0.3
